import React,{useState}from"react";
import ReactDOM from"react-dom/client";
import"./index.css";
const tools=[
["json","{}","JSON Formatter","Format, validate and minify JSON."],
["base64","B64","Base64 Encoder","Encode and decode Base64 locally."],
["url","↗","URL Encoder","Encode and decode URL components."],
["jwt","JWT","JWT Decoder","Decode JWT header and payload locally."],
["time","◷","Unix Timestamp","Convert timestamps and dates."],
["hash","#","SHA Hash Generator","Generate SHA-1, SHA-256 and SHA-512."],
["uuid","ID","UUID Generator","Generate secure UUID v4 values."],
["regex",".*","Regex Tester","Test JavaScript regular expressions."],
["color","HEX","Color Converter","Convert HEX colors to RGB."],
["text","Aa","Text Utilities","Count and transform text."],
["pass","•••","Password Generator","Generate strong passwords locally."],
["cron","CRON","Cron Helper","Generate common cron expressions."]
];
const copy=x=>x?navigator.clipboard?.writeText(x):null;
function Header({home}){return <header><a className="logo" href="#home" onClick={home}><b>404</b><span><strong>404Error.online</strong><small>Find the Error. Fix the Problem.</small></span></a><nav><a href="#home">Home</a><a href="#tools">Tools</a><a href="#errors">HTTP Errors</a><a href="#guides">Guides</a><a href="#cloud">Cloud</a></nav><a className="contact" href="mailto:hello@404error.online">Contact</a></header>}
function Shell({title,desc,back,children}){return <main className="workspace"><button className="back" onClick={back}>← Back to tools</button><div className="heading"><div className="eyebrow">404ERROR.ONLINE TOOL</div><h1>{title}</h1><p>{desc}</p></div><div className="panel">{children}</div></main>}
function Json(){let[a,setA]=useState('{"name":"404Error.online","active":true}'),[b,setB]=useState(""),[e,setE]=useState("");return <><div className="cols"><div><label>Input JSON</label><textarea value={a} onChange={x=>setA(x.target.value)}/></div><div><label>Result</label><textarea readOnly value={b} placeholder="Result..."/></div></div><div className="actions"><button onClick={()=>{try{setB(JSON.stringify(JSON.parse(a),null,2));setE("")}catch(x){setE(x.message)}}}>Format</button><button onClick={()=>{try{setB(JSON.stringify(JSON.parse(a)));setE("")}catch(x){setE(x.message)}}}>Minify</button><button onClick={()=>copy(b)}>Copy</button><button className="secondary" onClick={()=>{setA("");setB("");setE("")}}>Clear</button></div>{e&&<p className="error">{e}</p>}<Note/></>}
function Base64(){let[a,setA]=useState("Hello 404Error.online"),[b,setB]=useState(""),[mode,setMode]=useState("encode");const run=()=>{try{if(mode==="encode"){let x=new TextEncoder().encode(a),s="";x.forEach(v=>s+=String.fromCharCode(v));setB(btoa(s))}else{let s=atob(a.trim()),x=Uint8Array.from(s,c=>c.charCodeAt(0));setB(new TextDecoder().decode(x))}}catch{setB("Invalid Base64 input.")}};return <><div className="tabs"><button className={mode==="encode"?"on":""} onClick={()=>setMode("encode")}>Encode</button><button className={mode==="decode"?"on":""} onClick={()=>setMode("decode")}>Decode</button></div><label>Input</label><textarea value={a} onChange={x=>setA(x.target.value)}/><div className="actions"><button onClick={run}>{mode==="encode"?"Encode":"Decode"}</button><button onClick={()=>copy(b)}>Copy</button></div><label>Result</label><textarea readOnly value={b}/><Note/></>}
function Url(){let[a,setA]=useState("https://404error.online/search?q=hello world"),[b,setB]=useState(""),[mode,setMode]=useState("encode");return <><div className="tabs"><button className={mode==="encode"?"on":""} onClick={()=>setMode("encode")}>Encode</button><button className={mode==="decode"?"on":""} onClick={()=>setMode("decode")}>Decode</button></div><label>Input</label><textarea value={a} onChange={x=>setA(x.target.value)}/><div className="actions"><button onClick={()=>{try{setB(mode==="encode"?encodeURIComponent(a):decodeURIComponent(a))}catch{setB("Invalid URL encoding.")}}}>Run</button><button onClick={()=>copy(b)}>Copy</button></div><label>Result</label><textarea readOnly value={b}/></>}
function Jwt(){let[a,setA]=useState(""),[b,setB]=useState("");const run=()=>{try{let [h,p]=a.split("."),d=x=>JSON.parse(decodeURIComponent(escape(atob(x.replace(/-/g,"+").replace(/_/g,"/")))));setB("HEADER\\n"+JSON.stringify(d(h),null,2)+"\\n\\nPAYLOAD\\n"+JSON.stringify(d(p),null,2))}catch{setB("Invalid JWT format or payload.")}};return <><label>JWT token</label><textarea value={a} onChange={x=>setA(x.target.value)} placeholder="Paste a JWT here..."/><div className="actions"><button onClick={run}>Decode JWT</button><button onClick={()=>copy(b)}>Copy</button></div><pre>{b}</pre><p className="warn">⚠ Decoding does not verify the JWT signature. Do not paste sensitive production tokens.</p></>}
function Time(){let[t,setT]=useState(String(Math.floor(Date.now()/1000))),[d,setD]=useState(""),[r,setR]=useState("");return <><div className="two"><div><label>Unix timestamp</label><input value={t} onChange={x=>setT(x.target.value)}/><button onClick={()=>{let n=Number(t);setR(Number.isFinite(n)?new Date(n<1e12?n*1000:n).toISOString():"Invalid timestamp")}}>To date</button></div><div><label>Date/time</label><input type="datetime-local" value={d} onChange={x=>setD(x.target.value)}/><button onClick={()=>{let x=new Date(d);setR(isNaN(x)?"Invalid date":String(Math.floor(x.getTime()/1000)))}}>To timestamp</button></div></div><div className="result">{r||"Result will appear here"} <button onClick={()=>copy(r)}>Copy</button></div></>}
async function Hash(){let[a,setA]=useState("404Error.online"),[r,setR]=useState({});const run=async()=>{let d=new TextEncoder().encode(a),o={};for(let x of["SHA-1","SHA-256","SHA-512"]){let b=await crypto.subtle.digest(x,d);o[x]=[...new Uint8Array(b)].map(v=>v.toString(16).padStart(2,"0")).join("")}setR(o)};return <><label>Text</label><textarea value={a} onChange={x=>setA(x.target.value)}/><div className="actions"><button onClick={run}>Generate Hashes</button></div>{Object.entries(r).map(([k,v])=><div className="hash" key={k}><b>{k}</b><code>{v}</code><button onClick={()=>copy(v)}>Copy</button></div>)}<Note/></>}
function Uuid(){let[r,setR]=useState([]);return <><div className="actions"><button onClick={()=>setR(Array.from({length:10},()=>crypto.randomUUID()))}>Generate 10 UUIDs</button><button onClick={()=>copy(r.join("\n"))}>Copy All</button></div>{r.map(x=><div className="hash" key={x}><code>{x}</code><button onClick={()=>copy(x)}>Copy</button></div>)}</>}
function Regex(){let[p,setP]=useState("^hello"),[f,setF]=useState("gim"),[t,setT]=useState("Hello world\\nhello 404Error"),[r,setR]=useState([]);return <><div className="two"><div><label>Pattern</label><input value={p} onChange={x=>setP(x.target.value)}/></div><div><label>Flags</label><input value={f} onChange={x=>setF(x.target.value)}/></div></div><label>Test text</label><textarea value={t} onChange={x=>setT(x.target.value)}/><div className="actions"><button onClick={()=>{try{let q=new RegExp(p,f.includes("g")?f:f+"g");setR([...t.matchAll(q)].map(x=>x[0]))}catch(x){setR(["Error: "+x.message])}}}>Test</button></div><div className="matches">{r.length} match(es){r.map((x,i)=><div key={i}><code>{x}</code></div>)}</div></>}
function Color(){let[h,setH]=useState("#1684ff"),[r,setR]=useState("");return <><div className="swatch" style={{background:/^#[0-9a-f]{6}$/i.test(h)?h:"#64748b"}}/><div className="two"><div><label>HEX</label><input value={h} onChange={x=>setH(x.target.value)}/></div><div><label>RGB</label><input readOnly value={r}/></div></div><div className="actions"><button onClick={()=>{let x=h.replace("#","");if(x.length===3)x=x.split("").map(v=>v+v).join("");if(/^[0-9a-f]{6}$/i.test(x)){let n=parseInt(x,16);setR(`rgb(${n>>16}, ${(n>>8)&255}, ${n&255})`)}else setR("Invalid HEX")}}>Convert</button><button onClick={()=>copy(r)}>Copy</button></div></>}
function Text(){let[t,setT]=useState("404Error.online makes troubleshooting easier.");return <><label>Text</label><textarea value={t} onChange={x=>setT(x.target.value)}/><div className="stats"><b>{t.length}<small>Characters</small></b><b>{t.trim()?t.trim().split(/\\s+/).length:0}<small>Words</small></b><b>{t?t.split("\\n").length:0}<small>Lines</small></b></div><div className="actions"><button onClick={()=>setT(t.toUpperCase())}>UPPERCASE</button><button onClick={()=>setT(t.toLowerCase())}>lowercase</button><button onClick={()=>setT(t.trim().replace(/\\s+/g," "))}>Clean</button><button onClick={()=>copy(t)}>Copy</button></div></>}
function Pass(){let[n,setN]=useState(20),[p,setP]=useState("");return <><label>Length: {n}</label><input type="range" min="8" max="64" value={n} onChange={x=>setN(+x.target.value)}/><div className="password">{p||"Click Generate"}</div><div className="actions"><button onClick={()=>{let c="ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%^&*_-+=",a=new Uint32Array(n);crypto.getRandomValues(a);setP([...a].map(x=>c[x%c.length]).join(""))}}>Generate</button><button onClick={()=>copy(p)}>Copy</button></div><Note/></>}
function Cron(){let[o,setO]=useState("* * * * *"),p={"Every minute":"* * * * *","Every 5 minutes":"*/5 * * * *","Every hour":"0 * * * *","Every day at midnight":"0 0 * * *","Every day at 9 AM":"0 9 * * *","Every Monday at 9 AM":"0 9 * * 1","Every month":"0 0 1 * *"};return <><label>Preset</label><select value={o} onChange={x=>setO(x.target.value)}>{Object.entries(p).map(([k,v])=><option value={v} key={k}>{k} — {v}</option>)}</select><div className="cron">{o}</div><button onClick={()=>copy(o)}>Copy Cron</button></>}
function Note(){return <div className="note">🔒 This tool processes data in your browser. Nothing is uploaded by the tool.</div>}
const comps={json:Json,base64:Base64,url:Url,jwt:Jwt,time:Time,hash:Hash,uuid:Uuid,regex:Regex,color:Color,text:Text,pass:Pass,cron:Cron};
function App(){let[active,setActive]=useState(null),[q,setQ]=useState("");if(active){let t=tools.find(x=>x[0]===active),C=comps[active];return <><Header home={()=>setActive(null)}/><Shell title={t[2]} desc={t[3]} back={()=>setActive(null)}><C/></Shell><Footer/></>}return <div className="site"><Header/><section className="hero" id="home"><div><div className="eyebrow">TROUBLESHOOT • LEARN • SOLVE</div><h1>When Things Break,<br/><span>We Help You Fix Them.</span></h1><p>Practical troubleshooting, developer tools and step-by-step guides for Web, Cloud, DevOps and IT.</p><a className="heroBtn" href="#tools">Explore Free Tools →</a><small className="trust">✓ No signup &nbsp; ✓ Free &nbsp; ✓ Browser-based</small></div><div className="visual"><i>AWS</i><i>Kubernetes</i><i>Docker</i><div className="monitor"><b>404</b><strong>NOT FOUND?</strong><small>Don't worry...</small></div></div></section><section className="stats"><div><b>12+</b><span>Working Tools</span></div><div><b>100+</b><span>Planned Guides</span></div><div><b>0</b><span>Signup Required</span></div><div><b>100%</b><span>Client-side Tools</span></div></section><section className="section" id="tools"><div className="sectionTitle"><div><h2>Free Developer Tools</h2><p>Real interactive tools — not static demo cards.</p></div><input placeholder="Search tools..." value={q} onChange={x=>setQ(x.target.value)}/></div><div className="grid">{tools.filter(x=>(x[2]+x[3]).toLowerCase().includes(q.toLowerCase())).map(t=><button className="card" key={t[0]} onClick={()=>setActive(t[0])}><b>{t[1]}</b><h3>{t[2]}</h3><p>{t[3]}</p><span>Open Tool →</span></button>)}</div></section><section className="section" id="errors"><div className="sectionTitle"><div><h2>Common HTTP Errors</h2><p>Quick references for common status codes.</p></div></div><div className="errors">{[["400","Bad Request"],["401","Unauthorized"],["403","Forbidden"],["404","Not Found"],["500","Internal Server Error"],["502","Bad Gateway"],["503","Service Unavailable"]].map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>Understand the cause and troubleshooting steps.</p></article>)}</div></section><section className="section" id="guides"><div className="sectionTitle"><div><h2>Trending Guides</h2><p>A growing library for Cloud, DevOps and IT.</p></div></div><div className="guides">{["AWS","Kubernetes","Linux","DevOps"].map(x=><article key={x}><strong>{x}</strong><h3>Practical {x} troubleshooting guide</h3><p>Step-by-step solutions for common real-world issues.</p></article>)}</div></section><section className="cloud" id="cloud"><div><div className="eyebrow">CLOUD • DEVOPS • INFRASTRUCTURE</div><h2>Practical solutions for modern infrastructure.</h2><p>AWS, Azure, Kubernetes, Docker, Linux, Terraform and Jenkins.</p></div></section><Footer/></div>}
function Footer(){return <footer><b>404Error.online</b><p>Find the Error. Fix the Problem.</p><small>© 2026 404Error.online. All rights reserved.</small></footer>}
ReactDOM.createRoot(document.getElementById("root")).render(<App/>);
